---
kind: Service
apiVersion: v1
metadata:
  name: avalon-back-end-service
spec:
  type: ClusterIP
  selector:
    app: avalon-back-end
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: avalon-back-end
  name: avalon-back-end
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalon-back-end
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: avalon-back-end
    spec:
      containers:
      - image: tbrown1979/avalon-game:$LATEST_TAG
        name: avalon-back-end
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        resources: {}
status: {}
---