  name: CI
  on:
    pull_request
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: test
        run: sbt test